/*
SRC : SQL SERVER AND INFORMIX.
DEST : SQL SERVER.
*/

CREATE TABLE GLA_CONF_DET
(
CONF_ID   INT  IDENTITY(1,1),
SRC_TYP     NVARCHAR(10),
SRC_TYP_CD  CHAR(3),
DEST_TYP    NVARCHAR(10),
DEST_TYP_CD CHAR(3),
SRC_SRV_NM  NVARCHAR(100),
DEST_SRV_NM NVARCHAR(100),
SRC_DB_NM NVARCHAR(100),
TRG_DB_NM NVARCHAR(100),
SRC_DB_PWD NVARCHAR(100),
TRG_DB_PWD NVARCHAR(100),
)


